edited the login screen
idobarlev/Pomadero pull request #4
Opened 2021-06-21 18:11 UTC by YoniX44

Do it quickly IDO ya ben zona

2021-06-21 18:50 UTC, beneltayar commented
Put all images under the same folder (maybe `public/images/home_screen`)

2021-06-21 18:55 UTC, beneltayar requested changes

2021-06-21 18:55 UTC, beneltayar commented on src/Containers/Signin/Signin.js
> +            <img src={tile.img} alt={tile.title}/>
👍🏻

2021-06-21 18:55 UTC, beneltayar commented on src/Containers/Signin/tileData.js
> +        img: 'pizzaImg1.jpg',
add `title` to the tiles

- [ ] add `title`

2021-06-22 06:53 UTC, idobarlev commented on src/App.css
> +
Delete extra \n

2021-06-22 06:56 UTC, idobarlev commented on src/Containers/Home.js
> +const Home = (props) => {
It is possible to destruct user from props when receiving to component

Instead of: (props) -> ({user})

2021-06-22 06:58 UTC, idobarlev commented on src/Containers/Signin/Signin.style.js
> +    width: "240px"
Delete px (on default it is px)

2021-06-22 07:00 UTC, idobarlev commented on src/Containers/Signin/Signin.style.js
> +    marginLeft: "auto",
Switch to margin: 
margin: "0 auto"

2021-06-22 07:02 UTC, idobarlev commented on src/Containers/Signin/tileData.js
> +        title: "pizza image 1",
Choose one convention ' or "

2021-06-22 07:05 UTC, idobarlev commented on src/Containers/Home.js
> +const Home = (props) => {
If you decide to receive props delete wrapping ()

2021-06-22 07:06 UTC, idobarlev commented on src/Containers/Signin/Signin.style.js
> +    marginTop: "5vh",
why vh??

2021-06-22 07:07 UTC, idobarlev reviewed
Please fix!

2021-06-22 07:40 UTC, YoniX44 commented on src/Containers/Signin/Signin.style.js
> +    marginTop: "5vh",
so it will be dynamic and sexy in mobile

2021-06-22 08:06 UTC, idobarlev commented on src/Containers/Signin/Signin.style.js
> +    minWidth: "180px"
Delete all px 😡😡😡

2021-06-22 08:07 UTC, idobarlev reviewed
Delete all px 🐛

2021-06-22 08:33 UTC, idobarlev approved these changes
Approved!

2021-06-22 08:35 UTC, merged